openapi: 3.0.0
info:
  title: hello-service-api
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /hello:
    get:
      tags:
        - default
      summary: get
      parameters:
        - name: name
          in: query
          required: false
          schema:
            type: string
      responses:
        default:
          description: Default response
        '200':
          description: Successful response
          content:
            application/json: {}